---
- name: "NOTSCORED | CUSTOM | Enable logging for cron jobs"
  lineinfile:
    dest: /etc/rsyslog.d/50-default.conf
    regexp: "^#?cron\\.\\*\\s+\\/var\\/log\\/cron.log"
    line: "cron.*                         /var/log/cron.log"
    state: present

- name: "NOTSCORED | CUSTOM | /etc/sysctl.conf should be 0600"
  file:
    path: /etc/sysctl.conf
    mode: 0600
